import { DocumentedFile, DocumentedElement } from "../ai/client";
import { writeFile } from "../utils/file";
import * as path from "path";

export function generateMarkdown(
  documented: DocumentedFile,
  outDir: string,
  filePath: string
): string {
  const fileName = path.basename(filePath, path.extname(filePath));
  const outputPath = path.join(outDir, `${fileName}.md`);

  const lines: string[] = [];

  // Header
  lines.push(`# ${fileName}`);
  lines.push("");
  lines.push(`> **Language:** ${documented.language}`);
  lines.push(`> **Generated by:** fastdoc | ${new Date().toLocaleDateString()}`);
  lines.push("");
  lines.push("## Overview");
  lines.push("");
  lines.push(documented.description);
  lines.push("");
  lines.push("---");
  lines.push("");

  // Elements
  documented.elements.forEach((el) => {
    lines.push(...renderElement(el));
  });

  writeFile(outputPath, lines.join("\n"));
  return outputPath;
}

function renderElement(el: DocumentedElement): string[] {
  const lines: string[] = [];

  const emoji = {
    function: "🔧",
    class: "🏛️",
    interface: "📐",
    method: "⚙️",
    route: "🌐",
  }[el.type] ?? "📄";

  lines.push(`## ${emoji} \`${el.name}\``);
  lines.push("");
  lines.push(`**Type:** \`${el.type}\``);
  lines.push("");
  lines.push(el.description);
  lines.push("");

  // Signature
  lines.push("### Signature");
  lines.push("");
  lines.push("```");
  lines.push(el.signature);
  lines.push("```");
  lines.push("");

  // Parameters
  if (el.parameters && el.parameters.length > 0) {
    lines.push("### Parameters");
    lines.push("");
    lines.push("| Name | Type | Description |");
    lines.push("|------|------|-------------|");
    el.parameters.forEach((p) => {
      lines.push(`| \`${p.name}\` | \`${p.type}\` | ${p.description} |`);
    });
    lines.push("");
  }

  // Returns
  if (el.returns && el.returns.type && el.returns.type !== "void") {
    lines.push("### Returns");
    lines.push("");
    lines.push(`\`${el.returns.type}\` — ${el.returns.description}`);
    lines.push("");
  }

  // Example
  if (el.example) {
    lines.push("### Example");
    lines.push("");
    lines.push("```typescript");
    lines.push(el.example);
    lines.push("```");
    lines.push("");
  }

  // Warnings
  if (el.warnings) {
    lines.push("> ⚠️ **Warning:** " + el.warnings);
    lines.push("");
  }

  lines.push("---");
  lines.push("");

  return lines;
}